apiVersion: v1
kind: ConfigMap
metadata:
  name: ess-synapse
  namespace: ess
data:
  01-homeserver-underrides.yaml: |
    report_stats: true
    report_stats_endpoint: "http://matrix-housekeep.ess.svc.cluster.local/report-usage-stats/push"

    require_auth_for_profile_requests: true

    federation_client_minimum_tls_version: '1.2'

    experimental_features:
      msc4028_push_encrypted_events: true
    # The maximum allowed duration by which sent events can be delayed, as
    # per MSC4140.
    max_event_delay_duration: 24h

    rc_message:
      # This needs to match at least e2ee key sharing frequency plus a bit of headroom
      # Note key sharing events are bursty
      per_second: 0.5
      burst_count: 30

    rc_delayed_event_mgmt:
      # This needs to match at least the heart-beat frequency plus a bit of headroom
      # Currently the heart-beat is every 5 seconds which translates into a rate of 0.2s
      per_second: 1
      burst_count: 20
