apiVersion: v1
kind: ConfigMap
metadata:
  name: ess-synapse
  namespace: ess
data:
  01-homeserver-underrides.yaml: |
    report_stats: true
    report_stats_endpoint: "http://matrix-housekeep.ess.svc.cluster.local/report-usage-stats/push?access_token=dev-usage-token"
